### ISSUE TITLE
ApprArmor denies sigkill signal on Ubuntu 22.04.5 LTS, docker 24.0.5 (latest/stable)

### ISSUE THREAD

**Issue by Vlurk** [canonical/docker-snap#190]
I observe the behavior on Ubuntu 22.04.5 LTS, using snap package 24.0.5 (latest/stable).
It used to work fine previously, but likely stopped working with some updates in the last few months.

Upon doing a simple "docker container stop #containername#", three log entries will appear in dmesg:

- [992750.699273] audit: type=1400 audit(1730648846.097:83): apparmor="DENIED" operation="signal" profile="docker-default" pid=3479255 comm="runc" requested_mask="receive" denied_mask="receive" signal=term peer="snap.docker.dockerd
- [992752.754437] audit: type=1400 audit(1730648848.153:84): apparmor="DENIED" operation="signal" profile="docker-default" pid=3479261 comm="runc" requested_mask="receive" denied_mask="receive" signal=kill peer="snap.docker.dockerd"
- [992762.756895] audit: type=1400 audit(1730648858.156:85): apparmor="DENIED" operation="signal" profile="docker-default" pid=1676 comm="dockerd" requested_mask="receive" denied_mask="receive" signal=kill peer="snap.docker.dockerd"

The error received at the command line is simply:

`Error response from daemon: cannot stop container: #contername#: permission denied`

User initiating the command is a member of docker group, and the issue still occurs leveraging sudo privileges.

The workaround is simply `sudo kill #pid` the container process, and the container stops as expected.

**Comment by locnnil** [comment]
Hello, thank you for reporting this issue, we appreciate that.

This is a known issue already reported on: https://github.com/canonical/docker-snap/issues/36

We are working to solve this. But in the meantime, you may want to [try this workaround solution](https://github.com/canonical/docker-snap/issues/36#issuecomment-830320704).

**Comment by Vlurk** [comment]
This workaround didn't work for me.

I deleted the file as instructed and issued a "service docker restart" to restart the docker service.
I observed no change of behavior, including on a container I restarted

Reading a bit more about the issue, it appears like there was a regression already fixed by the official package. [https://github.com/moby/moby/pull/47749](url)

However, it hasn't been backported to 24.x because that branch is not maintained anymore.

**Comment by locnnil** [comment]
@Vlurk Thank you for the additional information!

The current version available on the [latest/stable channel](https://snapcraft.io/docs/channels) for the Docker snap is version 24.0.5, as shown by running:

```console
$ snap info docker
...
...
channels:
  latest/stable:    24.0.5   2024-09-03 (2932) 138MB -
  latest/candidate: 24.0.5   2024-09-03 (2932) 138MB -
  latest/beta:      27.2.0   2024-09-19 (2963) 146MB -
  latest/edge:      27.2.0   2024-09-20 (2969) 146MB -
  core18/stable:    20.10.17 2023-03-13 (2746) 146MB -
  core18/candidate: ↑
  core18/beta:      ↑
  core18/edge:      ↑
installed:          24.0.5              (2932) 138MB -
```

However, version `27.2.0` is currently available on the `beta` channel. 

We are currently testing the Docker snap on `beta` to ensure it runs smoothly without any regressions, and once these tests are complete, this version will be promoted to `stable`.

In the meantime, you may consider switching to the `beta` channel:
```bash
sudo snap refresh docker --beta
```

Once version `27.2.0` is promoted to `stable`, you can switch back to the stable channel:
```bash
sudo snap refresh docker --stable
```

**Comment by farshidtz** [comment]
Version `27.2.0` is now on latest/stable. This version includes the aforementioned fix: https://github.com/moby/moby/blob/v27.2.0/profiles/apparmor/template.go#L28-L31
